version: 3.15.0.{build}

branches:
  only:
  - master
  - step_metadata_support

image: Previous Visual Studio 2015

configuration: Release

clone_folder: c:/projects/openvsp

environment:
  matrix:
  - PYTHON: C:/Python27
    GENERATOR: Visual Studio 14 2015
    PYTHON_VERSION: 27
    ARCH: win32
  - PYTHON: C:/Python35
    GENERATOR: Visual Studio 14 2015
    PYTHON_VERSION: 35
    ARCH: win32
  - PYTHON: C:/Python36
    GENERATOR: Visual Studio 14 2015
    PYTHON_VERSION: 36
    ARCH: win32
  - PYTHON: C:/Python27-x64
    GENERATOR: Visual Studio 14 2015 Win64
    PYTHON_VERSION: 27
    ARCH: win64
  - PYTHON: C:/Python35-x64
    GENERATOR: Visual Studio 14 2015 Win64
    PYTHON_VERSION: 35
    ARCH: win64
  - PYTHON: C:/Python36-x64
    GENERATOR: Visual Studio 14 2015 Win64
    PYTHON_VERSION: 36
    ARCH: win64

install:
- cmd: choco install -y swig

build_script:
- cmd: >-

    cd C:/projects/openvsp

    mkdir install
    
    mkdir build
    
    cd build

    mkdir external
    
    mkdir vsp
    
    cd external

    cmake -G "%GENERATOR%" ^
    -DCMAKE_BUILD_TYPE=%configurtion% ^
    C:/projects/openvsp/Libraries
    
    msbuild /m:8 /verbosity:quiet /p:Configuration=%configuration% VSP_LIBRARIES.sln

    cd C:/projects/openvsp/build/vsp

    cmake -G "%GENERATOR%" ^
    -DCMAKE_BUILD_TYPE=%configuration% ^
    -DVSP_LIBRARY_PATH=C:/projects/openvsp/build/external ^
    -DPYTHON_INCLUDE_DIR=%PYTHON%/include ^
    -DPYTHON_LIBRARY=%PYTHON%/libs/python%PYTHON_VERSION%.lib ^
    -DCMAKE_INSTALL_PREFIX=C:/projects/openvsp/install ^
    C:/projects/openvsp/src

    msbuild /m:8 /verbosity:quiet /p:Configuration=%configuration% INSTALL.vcxproj

    cd C:/projects/openvsp

test: off

artifacts:
- path: install
  name: OpenVSP-3.15.0-%ARCH%-py%PYTHON_VERSION%

deploy: off